import defaultImage from "../assets/images/default-image.svg";
import autorImage from "../assets/images/circular-image.svg";

export const ARTICLES = [
  {
    lead: "Lead",
    title: "Title esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "Subhead. Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial",
    img: defaultImage,
    marquee: "Marquee",
    autor: "Author",
    imgautor: autorImage,
    url: "#",
  },
  {
    lead: "Lead",
    title: "Title esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "Subhead. Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial",
    img: defaultImage,
    marquee: "Marquee",
    autor: "Author",
    imgautor: autorImage,
    url: "#",
  },
  {
    lead: "Lead",
    title: "Title esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial",
    img: defaultImage,
    marquee: "Marquee",
    autor: "Author",
    imgautor: autorImage,
    url: "#",
  },
  {
    lead: "Lead",
    title: "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "Marquee",
    autor: "Author",
    imgautor: autorImage,
    url: "#",
  },
  {
    lead: "Lead",
    title: "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial",
    img: defaultImage,
    marquee: "Marquee",
    autor: "Author",
    imgautor: autorImage,
    url: "#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "Marquee",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "Marquee",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: defaultImage,
    marquee: "",
    autor: "Author",
    imgautor: "",
    url: "#",
  },
];
